name: Full release cycle

on:
  release:
    types: published
  workflow_dispatch:

jobs:

  one:
    uses: connorhsm/OneLife/.github/workflows/build-and-upload.yml@master # TO CHANGE

  two:
    needs: one
    uses: connorhsm/OneLife/.github/workflows/package-signed-windows-release.yml@master # TO CHANGE

  three:
    needs: two
    uses: connorhsm/OneLife/.github/workflows/build-diff-bundles.yml@master # TO CHANGE

  four:
    needs: three
    uses: connorhsm/OneLife/.github/workflows/clean-up-release.yml@master # TO CHANGE
     

# - Push release to reflector and update server?