name: Build Linux

on:
  push:
    branches: ["build-action"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: connorhsm/build-tools

      - run: ls
