name: Build Linux

on:
  # Intended use case, build on all published releases, everything else in place for testing
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: ["published"]
  push:
    branches: ["build-action"]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: connorhsm/build-tools

      # - name: Get release
      #   id: get_release
      #   uses: bruceadams/get-release@v1.2.3
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      - name: Prepare dependencies
        run: scripts/PrepareDependencies.sh
        shell: bash
      
      - name: Prepare repositories
        run: scripts/PrepareRepositories.sh
        shell: bash

      - name: Build
        run: scripts/BuildAndPostClients.sh linux client master
        shell: bash

      # - name: Upload release
      #   uses: actions/upload-release-asset@v1.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.get_release.outputs.upload_url }}
      #     asset_path: ./target/release/my-widget
      #     asset_name: my-widget
      #     asset_content_type: application/octet-stream

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: connorhsm/build-tools

      # - name: Get release
      #   id: get_release
      #   uses: bruceadams/get-release@v1.2.3
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      - name: Prepare dependencies
        run: scripts/PrepareDependencies.sh
        shell: bash
      
      - name: Prepare repositories
        run: scripts/PrepareRepositories.sh
        shell: bash

      - name: Link libs
        run: |
          sudo ln -s /bin/i686-w64-mingw32-g++ /usr/i686-w64-mingw32/bin/g++
          sudo ln -s /bin/i686-w64-mingw32-gcc /usr/i686-w64-mingw32/bin/gcc
          sudo ln -s /bin/i686-w64-mingw32-windres /usr/i686-w64-mingw32/bin/windres

      - name: Build
        run: scripts/BuildAndPostClients.sh windows client master
        shell: bash

      # - name: Upload release
      #   uses: actions/upload-release-asset@v1.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.get_release.outputs.upload_url }}
      #     asset_path: ./target/release/my-widget
      #     asset_name: my-widget
      #     asset_content_type: application/octet-stream