name: Build Linux

on:
  push:
    branches: ["build-action"]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: connorhsm/build-tools

      - name: ls
        run: ls

      - name: Install dependencies
        run: |
          ls
          ./scripts/PrepareDepencencies.sh
      
      - name: Ensure clean
        run: ./scripts/EnsureClean.sh

      - name: Build Linux
        run: ./scripts/BuildAndPostClients.sh linux client master
