name: Package signed windows release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  package-signed-windows-release:
    runs-on: ubuntu-latest
    steps:

      - name: Sleep for 5 minutes # to allow time for manual signing process
        run: sleep 300s
        shell: bash

      # FUTURE: Could we avoid redownloading? Instead of uploading in the calling workflow, just output for this workflow to later upload?
      # Is the time saved worth it?
      - name: Fetch signed binary
        id: fetch-binary
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          repo: connorhsm/OneLife # TO CHANGE
          file: 2HOL_.*(Windows\.zip|Signed\.exe)
          regex: true
          target: ./

        # Safety check that the manual signing process was completed.
      - name: Ensure correct assets downloaded
        run: |
          test -f 2HOL_Signed.exe || exit 2
          test -f 2HOL_v*_Windows.zip || exit 2

      - name: Insert signed binary to package
        id: insert-signed
        run: |
          ZIP_NAME=$(echo 2HOL_v*_Windows.zip)
          SHORT_NAME=2HOL_$(echo 2HOL_v*_Windows.zip | cut -d "_" -f 2)
          SIGNED_NAME=$(echo $SHORT_NAME)_Windows_Signed.zip
          unzip $ZIP_NAME
          mv 2HOL_Signed.exe $SHORT_NAME/2HOL.exe
          zip -r $SIGNED_NAME $SHORT_NAME
          echo "::set-output name=PACKAGE::$SIGNED_NAME"

      - name: Update release
        id: update_release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.fetch-binary.outputs.version }}

      - name: Delete unsigned package artifacts
        uses: mknejp/delete-release-assets@v1
        with: 
          token: ${{ github.token }}
          tag: ${{ steps.fetch-binary.outputs.version }}
          assets: |
            2HOL_v*_Windows.zip
            2HOL_Signed.exe
            2HOL_Unsigned.exe

      - name: Upload signed package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.event.release.upload_url }}
          asset_path: ${{ steps.insert-signed.outputs.PACKAGE }}
          asset_name: ${{ steps.insert-signed.outputs.PACKAGE }}
          asset_content_type: application/zip
