name: Package signed windows release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  package-signed-windows-release:
    runs-on: ubuntu-latest
    steps:

      # To allow time for manual signing process
      - name: Sleep
        run: sleep 150s
        shell: bash

      # LIMITATION: Downloads from the latest release, if a new release occurs between
      # the time the caller workflow is called and reaching this step, the job will fail.
      - name: Fetch signed binary
        id: fetch-binary
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          repo: connorhsm/OneLife # TO CHANGE
          file: 2HOL_.*(Windows\.zip|Signed\.exe)
          regex: true
          target: ./

        # Safety check that the manual signing process was completed.
      - name: Ensure correct assets downloaded
        run: |
          test -f 2HOL_Signed.exe || exit 2
          test -f 2HOL_v*_Windows.zip || exit 2

      - name: Insert signed binary to package
        id: insert-signed
        run: |
          ZIP_NAME=$(echo 2HOL_v*_Windows.zip)
          SHORT_NAME=2HOL_$(echo 2HOL_v*_Windows.zip | cut -d "_" -f 2)
          SIGNED_NAME=$(echo $SHORT_NAME)_Windows_Signed.zip
          unzip $ZIP_NAME
          mv 2HOL_Signed.exe $SHORT_NAME/2HOL.exe
          zip -r $SIGNED_NAME $SHORT_NAME
          echo "::set-output name=PACKAGE::$SIGNED_NAME"

      - name: Upload signed package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.insert-signed.outputs.PACKAGE }}
          asset_name: ${{ steps.insert-signed.outputs.PACKAGE }}
          asset_content_type: application/zip
