name: Release new version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build-target: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build-tools repo
        uses: actions/checkout@v3
        with:
          repository: connorhsm/build-tools

      #- name: Prepare dependencies
      #  run: scripts/PrepareDependencies.sh
      #  shell: bash
      
      #- name: Prepare repositories
      #  run: scripts/PrepareRepositories.sh
      #  shell: bash

      #- name: Link windows libs
      #  if: matrix.build-target == 'windows'
      #  run: |
      #    sudo ln -s /bin/i686-w64-mingw32-g++ /usr/i686-w64-mingw32/bin/g++
      #    sudo ln -s /bin/i686-w64-mingw32-gcc /usr/i686-w64-mingw32/bin/gcc
      #    sudo ln -s /bin/i686-w64-mingw32-windres /usr/i686-w64-mingw32/bin/windres

      #- name: Build client
      #  run: scripts/BuildAndPostClients.sh ${{ matrix.build-target }} client master unsigned
      #  shell: bash

      - run: |
          echo "REPLACE ME1!" > output/clientBuilds/assets1.txt
          echo "REPLACE ME2!" > output/clientBuilds/assets2.txt

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: assets*